## CARD Analysis File

```{r}
library (ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(ggpubr)
library(vegan)
library(plotly)
library(ggfortify)
library(compositions)
```

## Including Analysis

#### Load Pertinent Files

```{r}
metadata <- read.csv("metadata_updated.csv", header = TRUE)
metaxa_data <- read.delim("metaxa_genus.txt", header = TRUE)
card_data <- read.delim("card_genemat_no_zero.txt", header = TRUE)
drug_class_card <- read.delim("card_drug_class.txt", header = TRUE)
card_lengths <- read.delim("card_lengths.txt", header = TRUE)

```

#### Merging Metadata and Normalizing Counts using Metaxa

```{r}
# Transform Metaxa data to long format
long_metaxa <- metaxa_data %>%
  pivot_longer(cols = -Taxa, names_to = "SampleID", values_to = "Count")

# Merge Metaxa data with metadata
combined_metaxa <- merge(long_metaxa, metadata, by = "SampleID", all.x = TRUE)
combined_length <- merge (card_data, card_lengths, by = "GENE", all.x = TRUE)

ssu_counts <- combined_metaxa %>%
  group_by(SampleID) %>%
  summarize(SSU_Counts = sum(Count))

# Make GENE column into row names
rownames(combined_length) <- combined_length$GENE

# Remove GENE column
combined_length <- combined_length %>% select(-GENE)

# Normalize reads by gene lengths
card_length_norm <- combined_length[, 1:(ncol(combined_length)-1)]  / combined_length$Length

# Sort columns alphabetically to match with ssu_counts
card_length_norm <- card_length_norm[ , order(names(card_length_norm))]


# Normalization with Metaxa2 SSU counts
card_length_norm_t <- t(card_length_norm)
ssu_counts <- ssu_counts %>% select(-SampleID)
card_length_norm_t <- sweep(card_length_norm_t, 1, t(ssu_counts), FUN = "/")
card_length_SSU_norm <- t(card_length_norm_t) * 1540

row.names(card_length_SSU_norm)

# Replace counts in card_data with normalized values
normalized_card_data <- as.data.frame(card_length_SSU_norm) %>%
  mutate(GENE = rownames(card_length_SSU_norm)) %>%
  select(GENE, everything())

# Transform CARD data to long format
long_card <- normalized_card_data %>%
  pivot_longer(cols = -GENE, names_to = "SampleID", values_to = "Count")

# Merge CARD data with metadata
combined_data <- merge(long_card,metadata, by = "SampleID", all.x = TRUE)
print(combined_data)
combined_data_class <- merge(combined_data, drug_class_card, by = "GENE", all.x = TRUE)

# Reshape the data so that one row is one sample using pivot_wider
card_df <- combined_data %>%
  pivot_wider(names_from = GENE, values_from = Count)

```

#### Cleaning Drug Classes

```{r}
# Separating Multiple Drug Classes
combined_data_class <- combined_data_class %>%
  mutate(Class = str_replace_all(Class, "\\s*,\\s*", ","))

combined_data_class <- combined_data_class %>%
  separate_rows(Class, sep = ",") %>%
  mutate(Class = trimws(Class))

print (combined_data_class)
# 
# # Reshape the data so that one row is one sample using pivot_wider
# card_class <- combined_data_class %>% pivot_wider(names_from = Class, values_from = Count)
# 
# 
# card_class <- card_class %>%
#   mutate(across(everything(), ~ replace_na(.x, 0)))
# clean_names <- names(card_class)
# clean_names <- iconv(clean_names, from = "UTF-8", to = "ASCII//TRANSLIT")
# clean_names <- sub("^ ", "", clean_names)  # Adjusting the replacement pattern if necessary
# names(card_class) <- clean_names

# # Find duplicate column names
# duplicate_cols <- names(card_class)[duplicated(names(card_class))]
# 
# # Combine counts for duplicate columns
# for (col in unique(duplicate_cols)) {
#   cols_to_combine <- which(names(card_class) == col)
#   card_class[, col] <- rowSums(card_class[, cols_to_combine])
#   card_class <- card_class[, -cols_to_combine[-1]]
# }

# print (card_class)
# print (card_df)

# write.csv(card_class, "output.csv")
```

## Plots

## Relative abundances of Resistomes

### By Drug Class

```{r}

total_counts_per_sample <- combined_data_class %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

combined_data_temp <- combined_data_class

# Join the total counts back to the combined_data
combined_data_temp <- combined_data_temp %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 genes by average abundance
top_classes <- combined_data_temp %>%
  group_by(Class) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(Class)
class_viz <- combined_data_temp %>%
  mutate(Class = ifelse(Class %in% top_classes, Class, "Others"))

class_viz$Class <- factor(class_viz$Class, levels = c("Others", top_classes))

n_colors <- length(levels(class_viz$Class))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])


print (class_viz)

# Create the vertical bar plot using ggplot2, grouped by hospital
p <- ggplot(class_viz, aes(x = SampleID, y = Percentage, fill = Class)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  facet_wrap(~hospital, scales = "free_x") +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = " Top 15 Drug Classes Grouped by Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
         plot.margin = unit(c(1, 1, 1, 1), "cm"))


# Save plot
ggsave(filename = "plot1_drug_class_arg_ggplot.png",
     width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)
```

#### CGH

```{r}
# Filter data for the CGH hospital
cgh_data <- combined_data_class %>% filter(hospital == "CGH")

# Calculate the total count per sample for CGH
total_counts_per_sample <- cgh_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

# Join the total counts back to the CGH data
cgh_data <- cgh_data %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 classes by average abundance for CGH
top_classes <- cgh_data %>%
  group_by(Class) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(Class)

# Update the class_viz data with percentages and top classes
class_viz <- cgh_data %>%
  mutate(Class = ifelse(Class %in% top_classes, Class, "Others"))

class_viz$Class <- factor(class_viz$Class, levels = c("Others", top_classes))

n_colors <- length(levels(class_viz$Class))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(class_viz)

# Create the vertical bar plot using ggplot2, grouped by SampleID for CGH
p <- ggplot(class_viz, aes(x = SampleID, y = Percentage, fill = Class)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Drug Classes for CGH Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_drug_class_arg_cgh.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)

```

#### UST

```{r}

# Filter data for the UST hospital
UST_data <- combined_data_class %>% filter(hospital == "UST")

# Calculate the total count per sample for UST
total_counts_per_sample <- UST_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

# Join the total counts back to the UST data
UST_data <- UST_data %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 classes by average abundance for UST
top_classes <- UST_data %>%
  group_by(Class) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(Class)

# Update the class_viz data with percentages and top classes
class_viz <- UST_data %>%
  mutate(Class = ifelse(Class %in% top_classes, Class, "Others"))

class_viz$Class <- factor(class_viz$Class, levels = c("Others", top_classes))

n_colors <- length(levels(class_viz$Class))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(class_viz)

# Create the vertical bar plot using ggplot2, grouped by SampleID for UST
p <- ggplot(class_viz, aes(x = SampleID, y = Percentage, fill = Class)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Drug Classes for UST Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_drug_class_arg_UST.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)

```

#### SLMC

```{r}
# Filter data for the SLMC hospital
SLMC_data <- combined_data_class %>% filter(hospital == "SLMC")

# Calculate the total count per sample for SLMC
total_counts_per_sample <- SLMC_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

# Join the total counts back to the SLMC data
SLMC_data <- SLMC_data %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 classes by average abundance for SLMC
top_classes <- SLMC_data %>%
  group_by(Class) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(Class)

# Update the class_viz data with percentages and top classes
class_viz <- SLMC_data %>%
  mutate(Class = ifelse(Class %in% top_classes, Class, "Others"))

class_viz$Class <- factor(class_viz$Class, levels = c("Others", top_classes))

n_colors <- length(levels(class_viz$Class))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(class_viz)

# Create the vertical bar plot using ggplot2, grouped by SampleID for SLMC
p <- ggplot(class_viz, aes(x = SampleID, y = Percentage, fill = Class)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Drug Classes for SLMC Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_drug_class_arg_SLMC.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)

```

#### GENE ABUNDANCE PLOT

```{r}
# Per Gene
top_genes <- combined_data %>%
  group_by(GENE) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE)) %>%
  arrange(desc(TotalCount)) %>%
  top_n(15) %>%
  pull(GENE)

gene_viz <- combined_data %>%
  mutate(GENE = ifelse(GENE %in% top_genes, GENE, "Others"))

gene_viz$GENE <- factor(gene_viz$GENE, levels = c("Others", top_genes))

n_colors <- length(levels(gene_viz$GENE))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])


print (gene_viz)

# Create the vertical bar plot using ggplot2, grouped by hospital
p <- ggplot(gene_viz, aes(x = SampleID, y = Count, fill = GENE)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  facet_wrap(~hospital, scales = "free_x") +
  color_palette +
  labs(x = "Sample", y = "Normalized Count", title = " Top 15 Genes Grouped by Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
         plot.margin = unit(c(1, 1, 1, 1), "cm"))


# Save plot
ggsave(filename = "plot1_gene_count_arg_ggplot.png",
     width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)
```

```{r}

# Calculate the total count per sample
total_counts_per_sample <- combined_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

combined_data_temp <- combined_data

# Join the total counts back to the combined_data
combined_data_temp <- combined_data_temp %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 genes by average abundance
top_genes <- combined_data_temp %>%
  group_by(GENE) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(GENE)

# Update the gene_viz data with percentages and top genes
gene_viz <- combined_data_temp %>%
  mutate(GENE = ifelse(GENE %in% top_genes, GENE, "Others"))

gene_viz$GENE <- factor(gene_viz$GENE, levels = c("Others", top_genes))

n_colors <- length(levels(gene_viz$GENE))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(gene_viz)

# Create the vertical bar plot using ggplot2, grouped by hospital
p <- ggplot(gene_viz, aes(x = SampleID, y = Percentage, fill = GENE)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  facet_wrap(~hospital, scales = "free_x") +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Genes Grouped by Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_gene_count__rel_abundance_arg_ggplot.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)

```

```{r}

# Filter data for the CGH hospital
cgh_data <- combined_data %>% filter(hospital == "CGH")

# Calculate the total count per sample for CGH
total_counts_per_sample <- cgh_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

# Join the total counts back to the CGH data
cgh_data <- cgh_data %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 genes by average abundance for CGH
top_genes <- cgh_data %>%
  group_by(GENE) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(GENE)

# Update the gene_viz data with percentages and top genes
gene_viz <- cgh_data %>%
  mutate(GENE = ifelse(GENE %in% top_genes, GENE, "Others"))

gene_viz$GENE <- factor(gene_viz$GENE, levels = c("Others", top_genes))

n_colors <- length(levels(gene_viz$GENE))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(gene_viz)

# Create the vertical bar plot using ggplot2, grouped by SampleID for CGH
p <- ggplot(gene_viz, aes(x = SampleID, y = Percentage, fill = GENE)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Genes for CGH Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_gene_count_arg_cgh.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)

```

```{r}
# Filter data for the SLMC hospital
SLMC_data <- combined_data %>% filter(hospital == "SLMC")

# Calculate the total count per sample for SLMC
total_counts_per_sample <- SLMC_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

# Join the total counts back to the SLMC data
SLMC_data <- SLMC_data %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 genes by average abundance for SLMC
top_genes <- SLMC_data %>%
  group_by(GENE) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(GENE)

# Update the gene_viz data with percentages and top genes
gene_viz <- SLMC_data %>%
  mutate(GENE = ifelse(GENE %in% top_genes, GENE, "Others"))

gene_viz$GENE <- factor(gene_viz$GENE, levels = c("Others", top_genes))

n_colors <- length(levels(gene_viz$GENE))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(gene_viz)

# Create the vertical bar plot using ggplot2, grouped by SampleID for SLMC
p <- ggplot(gene_viz, aes(x = SampleID, y = Percentage, fill = GENE)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Genes for SLMC Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_gene_count_arg_SLMC.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)

```

```{r}

# Filter data for the UST hospital
UST_data <- combined_data %>% filter(hospital == "UST")

# Calculate the total count per sample for UST
total_counts_per_sample <- UST_data %>%
  group_by(SampleID) %>%
  summarise(TotalCount = sum(Count, na.rm = TRUE))

# Join the total counts back to the UST data
UST_data <- UST_data %>%
  left_join(total_counts_per_sample, by = "SampleID") %>%
  mutate(Percentage = (Count / TotalCount) * 100)

# Select the top 20 genes by average abundance for UST
top_genes <- UST_data %>%
  group_by(GENE) %>%
  summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
  arrange(desc(AverageAbundance)) %>%
  top_n(20, AverageAbundance) %>%
  pull(GENE)

# Update the gene_viz data with percentages and top genes
gene_viz <- UST_data %>%
  mutate(GENE = ifelse(GENE %in% top_genes, GENE, "Others"))

gene_viz$GENE <- factor(gene_viz$GENE, levels = c("Others", top_genes))

n_colors <- length(levels(gene_viz$GENE))
color_palette <- scale_fill_manual(values = c(brewer.pal(12, "Set3"), brewer.pal(8, "Pastel2"))[1:n_colors])

print(gene_viz)

# Create the vertical bar plot using ggplot2, grouped by SampleID for UST
p <- ggplot(gene_viz, aes(x = SampleID, y = Percentage, fill = GENE)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  color_palette +
  labs(x = "Sample", y = "Percentage", title = "Top 20 Genes for UST Hospital") +
  theme_light() +
  theme(legend.position = "right", 
        legend.title = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 8), # Adjust legend text size if necessary
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

# Save plot
ggsave(filename = "plot1_gene_count_arg_UST.png",
       width = 16, height = 8, dpi = 300, units = "in", device = 'png', scale = 1)
```

### PCA PLOT

```{r}

# Select the data for PCA
selected_data <- card_df %>% select(c(16:ncol(card_df)))
print(selected_data)

# Perform CLR transformation (assuming clr is defined elsewhere)
selected_data <- clr(selected_data)

# Perform PCA using RDA (vegan package)
pca_result <- rda(selected_data)

# Extract PCA scores for the samples (sites)
pca_scores <- scores(pca_result, display = "sites")
pca_data <- as.data.frame(pca_scores)  # Convert to data frame

# Add the hospital column to the PCA scores data frame
pca_data$hospital <- factor(card_df$hospital)
pca_data$SampleID <- card_df$SampleID
pca_data$month <- card_df$month

# Plotting using ggplot2
p <- ggplot(pca_data, aes(x = PC1, y = PC2, color = hospital, label = SampleID, group = hospital)) +
  geom_point(size = 4, alpha = 0.8) +
  geom_text(vjust = 1.5, hjust = 1.5, size = 3, check_overlap = TRUE) +
  stat_ellipse(level = 0.95, linetype = 2, aes(color = hospital), size = 1) +
  theme(text = element_text(family = "Palatino"),
        plot.title = element_text(size = 17, hjust = 0.5),
        axis.title = element_text(size = 17, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 17),
        legend.key.size = unit(1, 'cm'),
        legend.position = c(0.15, 0.9),
        legend.background = element_rect(color = "#ffffff"),
        legend.direction = "horizontal",
        axis.text = element_text(size = 17), aspect.ratio = 1) +
  scale_color_manual(values = c("#CD3857", "#61A6E3", "#CC7722"))
p + ggtitle("PCA, clr-transformed for three hospitals on ARG", subtitle = "CARD")

# Save the plot
ggsave(filename = "plot1_tax_pca_arg.png",
       width = 16, height = 13, dpi = 300, units = "in", device = 'png', scale = 1)

```
